################################################################
#
# Configuration for Traefik v2.
#
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: false

  websecure:
    address: ":443"
    http:
      tls: {}
  
  ping:
    address: ":8000"
  
  metrics:
    address: ":9000"

log:
  level: INFO

accessLog: {}

api:
  insecure: false
  dashboard: true

ping:
  entryPoint: ping

metrics:
  prometheus:
    addServicesLabels: true
    entryPoint: metrics

tracing:
  elastic:
    serverURL: "http://elastic_apm-server:8200"

providers:
  file:
    filename: /etc/traefik/dynamic.yml

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    network: backend
