cluster.name: "nader-cluster"
node.name: node-a
network.host: 0.0.0.0
transport.host: 0.0.0.0

# Development Settingss
discovery.type: single-node

# production settings
# cluster.initial_master_nodes:
#   - node-a

xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.key:  certs/elasticsearch/elasticsearch.key
xpack.security.http.ssl.certificate: certs/elasticsearch/elasticsearch.crt
xpack.security.http.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key:  certs/elasticsearch/elasticsearch.key
xpack.security.transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: [ "certs/ca/ca.crt" ]


# Enabling Elasticsearch native security realm
# https://www.elastic.co/guide/en/app-search/7.13/security-and-users.html#app-search-self-managed-security-and-user-management-elasticsearch-native-realm

xpack.security.authc.api_key.enabled: true
xpack:
  security:
    authc:
      realms:
        native:
          native1:
            order: 0
