# This file uses variable substitution
# To deploy to docker swarm use the following command
# docker stack deploy -c <(docker-compose --env-file docker.env config) mssql

version: "3.9"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:${TAG}

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 0
        order: stop-first

      resources:
        limits:
          # cpus: "2.0"
          memory: 4096M
        reservations:
          memory: 512M

    ports:
      - 1433:1433

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
