version: "3.9"

services:
    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest

        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 1
                delay: 30s
                order: start-first
                failure_action: rollback
                monitor: 30s
            rollback_config:
                parallelism: 0
                order: stop-first

        ports:
            - 1433:1433

        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P2ssw0rd!!
            - MSSQL_PID=Express
        volumes: 
            - db-data:/var/opt/mssql

            
volumes:
    db-data:

