# This file uses variable substitution
# To deploy to docker swarm use the following command
# docker stack deploy -c <(docker-compose --env-file docker.env config) jenkins

version: "3.9"

services:
  jenkins:
    image: drelshehabi/jenkins:${TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        order: stop-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 0
        order: stop-first

      resources:
        limits:
          # cpus: "1.0"
          memory: 1024M
        reservations:
          memory: 64M

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jenkins.rule=PathPrefix(`${PATH_PREFIX}`)"
        - "traefik.http.routers.jenkins.entrypoints=websecure"
        - "traefik.http.routers.jenkins.middlewares=jenkins-compress"
        - "traefik.http.services.jenkins-service.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.jenkins-compress.compress=true"

    environment:
      JENKINS_URL: ${JENKINS_URL}
      JENKINS_OPTS: --prefix=${PATH_PREFIX}

    volumes:
      - jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - backend

    configs:
      - source: jenkins-config
        target: /var/jenkins_home/jenkins-config.yml
      - source: jenkins-startup
        target: /usr/share/jenkins/ref/init.groovy.d/startup.groovy

    secrets:
      - jenkins-admin
      - jenkins-password

    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jenkins_home:

# Create this as driver=Overlay scope=swarm before deploying
networks:
  backend:
    external: true

configs:
  jenkins-config:
    name: ${JENKINS_CONFIG}
    file: ${JENKINS_CONFIG_FILE}
  jenkins-startup:
    name: ${JENKINS_STARTUP}
    file: ${JENKINS_STARTUP_FILE}

secrets:
  jenkins-admin:
    name: ${JENKINS_ADMIN}
    file: ${JENKINS_ADMIN_FILE}
  jenkins-password:
    name: ${JENKINS_PASSWORD}
    file: ${JENKINS_PASSWORD_FILE}
