version: "3.9"

services:
  jenkins:
    image: drelshehabi/jenkins:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 0
        order: stop-first

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)"
        - "traefik.http.routers.jenkins.entrypoints=websecure"
        - "traefik.http.routers.jenkins.middlewares=jenkins-compress"
        - "traefik.http.services.jenkins-service.loadbalancer.server.port=8080"
        - "traefik.http.middlewares.jenkins-compress.compress=true"

    environment:
      JENKINS_URL: https://localhost/jenkins
      JENKINS_OPTS: --prefix=/jenkins

    volumes:
      - jenkins_home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - backend

    configs:
      - source: JENKINS_CONFIG
        target: /var/jenkins_home/jenkins-config.yml
      - source: JENKINS_STARTUP
        target: /usr/share/jenkins/ref/init.groovy.d/startup.groovy

    secrets:
      - JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD

    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  jenkins_home:

# Create this as driver=Overlay scope=swarm before deploying
networks:
  backend:
    external: true

configs:
  JENKINS_CONFIG:
    file: ./jenkins-config.yml
  JENKINS_STARTUP:
    file: ./startup.groovy

secrets:
  JENKINS_ADMIN_ID:
    file: ./secrets/jenkins_admin_id.txt
  JENKINS_ADMIN_PASSWORD:
    file: ./secrets/jenkins_admin_password.txt
